CommunicatieAppBackend/Models/Handleiding.cs
namespace CommunicatieAppBackend.Models;
public class Handleiding {
    public int id {get;set;}
    public String Title {get;set;}
    public String Details {get;set;}
    public String Document {get;set;}

}

CommunicatieAppBackend/Models/HandleidingViewModel.cs
namespace CommunicatieAppBackend.Models;
public class HandleidingViewModel
{
    public Handleiding Handleiding { get; set; }
    public IFormFile? Document { get; set; }
}

CommunicatieAppBackend/Controllers/HandleidingController.cs
using CommunicatieAppBackend.DTOs;
using CommunicatieAppBackend.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CommunicatieAppBackend.Controllers;

public class HandleidingController : Controller{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _environment;

    public HandleidingController(AppDbContext context, IWebHostEnvironment environment)
    {
        _context = context;
        _environment = environment;
    }

    [Authorize(Roles = "Admin")]
    public async Task<ViewResult> Index() => View(await _context.Handleidingen.ToListAsync());
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create()
    {
        return View(new HandleidingViewModel());
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(HandleidingViewModel model)
    {
        if (model.Document == null || model.Document.Length == 0)
        {
            return Content("File not selected");
        }
        var path = Path.Combine(_environment.WebRootPath, "Document\\Handleiding", model.Document.FileName);
        Console.WriteLine(path);

        using (FileStream stream = new FileStream(path, FileMode.Create))
        {
            await model.Document.CopyToAsync(stream);
            stream.Close();
        }

        model.Handleiding.Document = model.Document.FileName;

        if (model != null)
        {
            Console.WriteLine(model.Handleiding.Document);
            var handleiding = new Handleiding
            {
                Title = model.Handleiding.Title,
                Details = model.Handleiding.Details,
                Document = model.Handleiding.Document,
                id = model.Handleiding.id
            };
            _context.Add(handleiding);
            await _context.SaveChangesAsync();
        }
        return RedirectToAction(nameof(Index));

    }

    [Authorize(Roles = "Admin")]    
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Handleidingen == null)
        {
            return NotFound();
        }

        var Handleiding = await _context.Handleidingen.FirstOrDefaultAsync(it=>it.id==id);
        if (Handleiding == null)
        {
            return NotFound();
        }
        var path = Path.Combine(_environment.WebRootPath, "Document/Handleiding", Handleiding.Document);
        using (var stream = System.IO.File.OpenRead(path))
        {
        IEnumerable<Locatie> locaties = await _context.Locaties.ToListAsync();
        return View(new HandleidingViewModel{
            Handleiding = Handleiding,
            Document = new FormFile(stream, 0, stream.Length, null, Path.GetFileName(stream.Name)),
            });
        }

    }

    // POST: handleidingen/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [Authorize(Roles = "Admin")]
    [HttpPost]
    [ValidateAntiForgeryToken]  
    // [Route("Handleiding/Edit")]  
    public async Task<IActionResult> Edit(int id, HandleidingViewModel model)
    {
        // Console.WriteLine(handleidingViewModel.Locaties.First());
        if (id != model.Handleiding.id)
        {
            return NotFound();
        }
        if (model.Document != null && model.Document.Length > 0)
        {
            var path = Path.Combine(_environment.WebRootPath, "Document/Handleiding", model.Document.FileName);
            Console.WriteLine(path);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await model.Document.CopyToAsync(stream);
                stream.Close();
            }

            model.Handleiding.Document = model.Document.FileName;
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model.Handleiding);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HandleidingExists(model.Handleiding.id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    [Authorize(Roles = "Admin")]
    private bool HandleidingExists(int id)
    {
        return _context.Handleidingen.Any(e => e.id == id);
    }


    // GET: handleidingen/Delete/5
    // [Route("Delete")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Handleidingen == null)
        {
            return NotFound();
        }

        var Handleiding = await _context.Handleidingen
            .FirstOrDefaultAsync(m => m.id == id);
        if (Handleiding == null)
        {
            return NotFound();
        }

        return View(Handleiding);
    }
        // POST: nieuwsberichten/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    // [Route("DeleteConfirm")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        if (_context.Handleidingen == null)
        {
            return Problem("Entity set 'PocketSkillsDbContext.nieuwsberichten'  is null.");
        }
        var handleiding = await _context.Handleidingen.SingleOrDefaultAsync(it=>it.id==id);
        if (handleiding != null)
        {
            Console.WriteLine("removing "+handleiding.id+" "+handleiding.Title+" "+handleiding.Details);
            _context.Handleidingen.Remove(handleiding);
            _context.SaveChanges();
        }
        return RedirectToAction(nameof(Index));
    }


    [HttpGet]
    [Route("Handleiding/Get")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
    public async Task<GetHandleidingDTO> getAll(){
        return new GetHandleidingDTO
        {
            Handleidingen = await _context.Handleidingen.ToListAsync()
        };
    }

    [Authorize(Roles = "Admin")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Handleidingen == null)
        {
            return NotFound();
        }

        var handleiding = await _context.Handleidingen.FirstOrDefaultAsync(m => m.id == id);
        if (handleiding == null)
        {
            return NotFound();
        }

        return View(handleiding);
    }
} 

CommunicatieAppBackend/Views/Handleiding/Create.cshtml
@model CommunicatieAppBackend.Models.HandleidingViewModel

@{
    ViewData["Title"] = "Create";
    String defaultdt = DateTime.Now.ToString("yyyy-MM-ddThh:mm");
}

<h1>Create</h1>

<h4>Handleiding</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Handleiding" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <input type="hidden" asp-for="HandleidingId" /> *@
            <div class="form-group">
                <label asp-for="Handleiding.Title" class="control-label"></label>
                <input asp-for="Handleiding.Title" class="form-control" />
                <span asp-validation-for="Handleiding.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Handleiding.Details" class="control-label"></label>
                <input asp-for="Handleiding.Details" class="form-control" />
                <span asp-validation-for="Handleiding.Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Document" class="control-label"></label>
                <input asp-for="Document" class="form-control">
                @* <div id="chooseFile"><input type="file" name="Foto" accept="image/*" /></div> *@
                <span asp-validation-for="Document" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Handleiding" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunicatieAppBackend/Views/Handleiding/Delete.cshtml
@model CommunicatieAppBackend.Models.Handleiding

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nieuwsbericht</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(it=>it.Document)
        </dt>
        <dd class = "col-sm-10">
            <a href="~/Document/Handleiding/@Html.DisplayFor(model => model.Document)">Download de handleiding</a>
        </dd>
    </dl>
    
    <form asp-controller="Handleiding" asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Handleiding" asp-action="Index">Back to List</a>
    </form>
</div>

CommunicatieAppBackend/Views/Handleiding/Details.cshtml
@model CommunicatieAppBackend.Models.Handleiding

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Handleiding</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Document)
        </dt>
        <dd class = "col-sm-10">
            <a href="~/Document/Handleiding/@Html.DisplayFor(model => model.Document)">Download de handleiding</a>
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Handleiding" asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-controller="Handleiding" asp-action="Index">Back to List</a>
</div>

CommunicatieAppBackend/Views/Handleiding/Edit.cshtml
@model CommunicatieAppBackend.Models.HandleidingViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Handleiding</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Handleiding" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Handleiding.id" />
            <div class="form-group">
                <label asp-for="Handleiding.Title" class="control-label"></label>
                <input asp-for="Handleiding.Title" class="form-control" />
                <span asp-validation-for="Handleiding.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Handleiding.Details" class="control-label"></label>
                <input asp-for="Handleiding.Details" class="form-control" />
                <span asp-validation-for="Handleiding.Details" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Handleiding.Datum" class="control-label"></label>
                <input asp-for="Handleiding.Datum" class="form-control" />
                <span asp-validation-for="Handleiding.Datum" class="text-danger"></span>
            </div> *@
            @* <div class="form-group">
                <label asp-for="Handleiding.Image" class="control-label"></label>
                <input asp-for="Handleiding.Image" class="form-control" />
                <span asp-validation-for="Handleiding.Image" class="text-danger"></span>
            </div> *@
            @* <div class="form-group">
                <label asp-for="Handleiding.Locatie"></label>
                <input type="hidden" asp-for="Handleiding.Locatie.name"></input>
                <br/>
                <input asp-for="Locaties" type="hidden"></input>
                @Html.DropDownListFor(
                    m=>m.Handleiding.LocatieId,
                    new SelectList(Model.Locaties,"Id","name",Model.Locaties.SingleOrDefault(it=>it.Id==Model.Handleiding.LocatieId)),
                    "--select--"
                )
            </div> *@
            <div class="form-group">
                Nieuwe <label asp-for="Document" class="control-label"></label>
                <input asp-for="Document" class="form-control">
                <input type="hidden" asp-for="Handleiding.Document" class="form-control">
                @* <div id="chooseFile"><input type="file" name="Foto" accept="image/*" /></div> *@
                <span asp-validation-for="Document" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunicatieAppBackend/Views/Handleiding/Index.cshtml
@model IEnumerable<CommunicatieAppBackend.Models.Handleiding>

@{
    ViewData["Title"] = "Index";
}

<h1>Handleidingen</h1>
<p>
    <a asp-controller="Handleiding" asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("Index", "Handleiding", FormMethod.Get))
{
<text>Search:</text> @Html.TextBox("searchString")<input type="submit" name="submit" value="Search" />
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Document)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Title)
            </td>
            <td>
                @Html.DisplayFor(model => item.Details)
            </td>
            <td>
                <a href="Document/Handleiding/@item.Document">@Html.DisplayFor(model => item.Document)</a>
            </td>
            <td>
                <a asp-controller="Handleiding" asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-controller="Handleiding" asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-controller="Handleiding" asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>