CommunicatieAppBackend/Models/Nieuwsbericht.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommunicatieAppBackend.Models;

public class Nieuwsbericht{
    [Key]
    public int NieuwsberichtId { get; set; }
    public String Titel { get; set; }
    public String Inhoud { get; set; }
    public String? Image { get; set; }    
    public DateTime Datum { get; set; }
    [ForeignKey("Locatie")]
    public int LocatieId {get;set;}
    public Locatie Locatie {get;set;}

}

CommunicatieAppBackend/Models/NieuwsberichtViewModel.cs
namespace CommunicatieAppBackend.Models;
public class NieuwsberichtViewModel
    {
        public Nieuwsbericht? nieuwsbericht { get; set; }
        public IFormFile? Foto { get; set; }
        public IEnumerable<Locatie> Locaties {get; set;}
    }
    

CommunicatieAppBackend/Controllers/NieuwsberichtController.cs
using CommunicatieAppBackend.DTOs;
using CommunicatieAppBackend.Hubs;
using CommunicatieAppBackend.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace CommunicatieAppBackend.Controllers;
public class NieuwsberichtController : Controller
{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _environment;

    private IHubContext<NotificationHub> HubContext{ get; set; }


    public NieuwsberichtController(AppDbContext context, IWebHostEnvironment environment, IHubContext<NotificationHub> hubContext)
    {
        HubContext = hubContext;
        _context = context;
        _environment = environment;
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index(String searchString)
    {
        if (searchString != null)
        {
            return View(_context.nieuwsberichten.Where(x => x.Titel.Contains(searchString) || searchString == null).Include(m=>m.Locatie).ToList());
        }
        return View(await _context.nieuwsberichten.Include(m=>m.Locatie).ToListAsync());
    }

    // GET: nieuwsberichten/Details/5
    // [Route("Details")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.nieuwsberichten == null)
        {
            return NotFound();
        }

        var Nieuwsbericht = await _context.nieuwsberichten.Include(it=>it.Locatie)
            .FirstOrDefaultAsync(m => m.NieuwsberichtId == id);
        if (Nieuwsbericht == null)
        {
            return NotFound();
        }

        return View(Nieuwsbericht);
    }

    // GET: nieuwsberichten/Create
    // [Route("Create")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create()
    {
        var locaties = await _context.Locaties.ToListAsync();
        return View(new NieuwsberichtViewModel{
            Locaties= locaties
        });
    }

    // POST: nieuwsberichten/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    // [Route("Create")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create(NieuwsberichtViewModel model)
    {
        if (model.Foto == null || model.Foto.Length == 0)
        {
            return Content("File not selected");
        }
        var path = Path.Combine(_environment.WebRootPath, "Image\\Nieuws", model.Foto.FileName);
        Console.WriteLine(path);

        using (FileStream stream = new FileStream(path, FileMode.Create))
        {
            await model.Foto.CopyToAsync(stream);
            stream.Close();
        }

        model.nieuwsbericht.Image = model.Foto.FileName;

        if (model != null)
        {
            Console.WriteLine(model.nieuwsbericht.Image);
            var nieuwsbericht = new Nieuwsbericht
            {
                Titel = model.nieuwsbericht.Titel,
                Inhoud = model.nieuwsbericht.Inhoud,
                Datum = model.nieuwsbericht.Datum,
                Image = model.nieuwsbericht.Image,
                LocatieId = model.nieuwsbericht.LocatieId
                // ImageLocation = path,
            };
            _context.Add(nieuwsbericht);
            await _context.SaveChangesAsync();
            await HubContext.Clients.All.SendAsync("ReceiveNotification",nieuwsbericht.Titel,nieuwsbericht.Inhoud, nieuwsbericht.Image);
        }
        return RedirectToAction(nameof(Index));

        // Nieuwsbericht.NieuwsberichtId=await _context.nieuwsberichten.MaxAsync(it=>it.NieuwsberichtId)+1;
        // Console.WriteLine("creating "+Nieuwsbericht.NieuwsberichtId+"..");
        
        // if (ModelState.IsValid)
        // {
        //     _context.Add(Nieuwsbericht);
        //     await _context.SaveChangesAsync();
        //     return RedirectToAction(nameof(Index));
        // } else Console.WriteLine("creating failed");
        // return View(Nieuwsbericht);
    }

    // GET: nieuwsberichten/Edit/5
    // [Route("Nieuwsbericht/Edit")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.nieuwsberichten == null)
        {
            return NotFound();
        }

        var Nieuwsbericht = await _context.nieuwsberichten.Include(it=>it.Locatie).FirstOrDefaultAsync(it=>it.NieuwsberichtId==id);
        if (Nieuwsbericht == null)
        {
            return NotFound();
        }
        var path = Path.Combine(_environment.WebRootPath, "Image\\Nieuws", Nieuwsbericht.Image);
        using (var stream = System.IO.File.OpenRead(path))
        {
        IEnumerable<Locatie> locaties = await _context.Locaties.ToListAsync();
        return View(new NieuwsberichtViewModel{
            nieuwsbericht = Nieuwsbericht,
            Locaties = locaties,
            Foto = new FormFile(stream, 0, stream.Length, null, Path.GetFileName(stream.Name)),
            });
        }

    }

    // POST: nieuwsberichten/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]  
    // [Route("Nieuwsbericht/Edit")]  
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(int id, NieuwsberichtViewModel model)
    {
        // Console.WriteLine(nieuwsberichtViewModel.Locaties.First());
        if (id != model.nieuwsbericht.NieuwsberichtId)
        {
            return NotFound();
        }
        if (model.Foto != null && model.Foto.Length > 0)
        {
            var path = Path.Combine(_environment.WebRootPath, "Image/Nieuws", model.Foto.FileName);
            Console.WriteLine(path);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await model.Foto.CopyToAsync(stream);
                stream.Close();
            }

            model.nieuwsbericht.Image = model.Foto.FileName;
        }
        model.nieuwsbericht.Locatie=await _context.Locaties.SingleOrDefaultAsync(it=>it.Id==model.nieuwsbericht.LocatieId);

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model.nieuwsbericht);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NieuwsberichtExists(model.nieuwsbericht.NieuwsberichtId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        var errors = ModelState.Where(x => x.Value.Errors.Any())
                .Select(x => new { x.Key, x.Value.Errors });
        foreach (var err in errors){
            Console.WriteLine(err);
            foreach (var item in err.Errors)
            {
                Console.WriteLine(item.ErrorMessage);

            }
        }
        IEnumerable<Locatie> locaties = await _context.Locaties.ToListAsync();
        model.Locaties=locaties;
        foreach (var loc in locaties)
        {
            Console.WriteLine(loc.name);
        }

        // return RedirectToAction(nameof(Index));

        return View(model);
    }

    // GET: nieuwsberichten/Delete/5
    // [Route("Delete")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.nieuwsberichten == null)
        {
            return NotFound();
        }

        var Nieuwsbericht = await _context.nieuwsberichten
            .FirstOrDefaultAsync(m => m.NieuwsberichtId == id);
        if (Nieuwsbericht == null)
        {
            return NotFound();
        }

        return View(Nieuwsbericht);
    }

    // POST: nieuwsberichten/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    // [Route("DeleteConfirm")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        if (_context.nieuwsberichten == null)
        {
            return Problem("Entity set 'PocketSkillsDbContext.nieuwsberichten'  is null.");
        }
        var Nieuwsbericht = await _context.nieuwsberichten.SingleOrDefaultAsync(it=>it.NieuwsberichtId==id);
        if (Nieuwsbericht != null)
        {
            Console.WriteLine("removing "+Nieuwsbericht.NieuwsberichtId+" "+Nieuwsbericht.Titel+" "+Nieuwsbericht.Inhoud+" "+Nieuwsbericht.Datum);
            _context.nieuwsberichten.Remove(Nieuwsbericht);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        else return NotFound();
    }

    [Authorize(Roles = "Admin")]
    private bool NieuwsberichtExists(int id)
    {
        return _context.nieuwsberichten.Any(e => e.NieuwsberichtId == id);
    }

    [HttpGet]
    [Route("Nieuwsbericht/Get")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
    public async Task<GetNieuwsberichtDTO> getAll(){    
        return new GetNieuwsberichtDTO
        {
            Nieuwsberichten = await _context.nieuwsberichten.Include(m=>m.Locatie).ToListAsync()
        };
    }

    [HttpGet]
    [Route("Nieuwsbericht/GetByLocatie/{id}")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
    public async Task<GetNieuwsberichtDTO> getByLocatie(String id){
        return new GetNieuwsberichtDTO
        {
            Nieuwsberichten = await _context.nieuwsberichten.Include(m=>m.Locatie).Where(n=>n.Locatie.name==id).ToListAsync()
        };
    }
}

CommunicatieAppBackend/Views/Nieuwsbericht/Create.cshtml
@model CommunicatieAppBackend.Models.NieuwsberichtViewModel

@{
    ViewData["Title"] = "Create";
    String defaultdt = DateTime.Now.ToString("yyyy-MM-ddThh:mm");
}

<h1>Create</h1>

<h4>Nieuwsbericht</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Nieuwsbericht" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <input type="hidden" asp-for="NieuwsberichtId" /> *@
            <div class="form-group">
                <label asp-for="nieuwsbericht.Titel" class="control-label"></label>
                <input asp-for="nieuwsbericht.Titel" class="form-control" />
                <span asp-validation-for="nieuwsbericht.Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nieuwsbericht.Inhoud" class="control-label"></label>
                <input asp-for="nieuwsbericht.Inhoud" class="form-control" />
                <span asp-validation-for="nieuwsbericht.Inhoud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nieuwsbericht.Datum" class="control-label"></label>
                <input type="datetime-local" asp-for="nieuwsbericht.Datum" class="form-control" value="@defaultdt" />
                <span asp-validation-for="nieuwsbericht.Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nieuwsbericht.Locatie"></label>
                <br/>
                @Html.DropDownListFor(
                    m=>m.nieuwsbericht.LocatieId,
                    new SelectList(Model.Locaties,"Id","name",Model.Locaties.FirstOrDefault()),
                    "--select--"
                )
                @* <label asp-for="Locaties" class="control-label"></label>
                <input type="datetime-local" asp-for="nieuwsbericht.Datum" class="form-control" value="@defaultdt" />
                <span asp-validation-for="nieuwsbericht.Datum" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control">
                @* <div id="chooseFile"><input type="file" name="Foto" accept="image/*" /></div> *@
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="nieuwsbericht.Image"/>
            <input type="hidden" asp-for="Locaties"/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Nieuwsbericht" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunicatieAppBackend/Views/Nieuwsbericht/Delete.cshtml
@model CommunicatieAppBackend.Models.Nieuwsbericht

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nieuwsbericht</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inhoud)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inhoud)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(it=>it.Image)
        </dt>
        <dd class = "col-sm-10">
            <img height="300" src="~/Image/Nieuws/@Html.DisplayFor(model => model.Image)"></img>
        </dd>
    </dl>
    
    <form asp-controller="Nieuwsbericht" asp-action="Delete">
        <input type="hidden" asp-for="NieuwsberichtId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Nieuwsbericht" asp-action="Index">Back to List</a>
    </form>
</div>

CommunicatieAppBackend/Views/Nieuwsbericht/Details.cshtml
@model CommunicatieAppBackend.Models.Nieuwsbericht

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Nieuwsbericht</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inhoud)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inhoud)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locatie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locatie.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(it=>it.Image)
        </dt>
        <dd>
            <img height="300" src="~/Image/Nieuws/@Html.DisplayFor(model => model.Image)"></img>
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Nieuwsbericht" asp-action="Edit" asp-route-id="@Model?.NieuwsberichtId">Edit</a> |
    <a asp-controller="Nieuwsbericht" asp-action="Index">Back to List</a>
</div>

CommunicatieAppBackend/Views/Nieuwsbericht/Edit.cshtml
@model CommunicatieAppBackend.Models.NieuwsberichtViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Nieuwsbericht</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Nieuwsbericht" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="nieuwsbericht.NieuwsberichtId" />
            <div class="form-group">
                <label asp-for="nieuwsbericht.Titel" class="control-label"></label>
                <input asp-for="nieuwsbericht.Titel" class="form-control" />
                <span asp-validation-for="nieuwsbericht.Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nieuwsbericht.Inhoud" class="control-label"></label>
                <input asp-for="nieuwsbericht.Inhoud" class="form-control" />
                <span asp-validation-for="nieuwsbericht.Inhoud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nieuwsbericht.Datum" class="control-label"></label>
                <input asp-for="nieuwsbericht.Datum" class="form-control" />
                <span asp-validation-for="nieuwsbericht.Datum" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="nieuwsbericht.Image" class="control-label"></label>
                <input asp-for="nieuwsbericht.Image" class="form-control" />
                <span asp-validation-for="nieuwsbericht.Image" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="nieuwsbericht.Locatie"></label>
                <input type="hidden" asp-for="nieuwsbericht.Locatie.name"></input>
                <br/>
                <input asp-for="Locaties" type="hidden"></input>
                @Html.DropDownListFor(
                    m=>m.nieuwsbericht.LocatieId,
                    new SelectList(Model.Locaties,"Id","name",Model.Locaties.SingleOrDefault(it=>it.Id==Model.nieuwsbericht.LocatieId)),
                    "--select--"
                )
                @* <label asp-for="Locaties" class="control-label"></label>
                <input type="datetime-local" asp-for="nieuwsbericht.Datum" class="form-control" value="@defaultdt" />
                <span asp-validation-for="nieuwsbericht.Datum" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                Nieuwe <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control">
                <label>Huidige foto:</label>
                <input type="hidden" asp-for="nieuwsbericht.Image" class="form-control">
                <img height="300" src="~/Image/Nieuws/@Html.DisplayFor(model => model.nieuwsbericht.Image)"></img>
                @* <div id="chooseFile"><input type="file" name="Foto" accept="image/*" /></div> *@
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunicatieAppBackend/Views/Nieuwsbericht/Index.cshtml
@model IEnumerable<CommunicatieAppBackend.Models.Nieuwsbericht>

@{
    ViewData["Title"] = "Index";
}

<h1>Nieuwsberichten</h1>

<p>
    <a asp-controller="Nieuwsbericht" asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("Index", "Nieuwsberichten", FormMethod.Get))
{
<text>Search:</text> @Html.TextBox("searchString")<input type="submit" name="submit" value="Search" />
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inhoud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Locatie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Titel)
            </td>
            <td>
                @Html.DisplayFor(model => item.Inhoud)
            </td>
            <td>
                @Html.DisplayFor(model => item.Datum)
            </td>
            <td>
                <img height="300" src="~/Image/Nieuws/@Html.DisplayFor(model => item.Image)"></img>
            </td>
            <td>
                @Html.DisplayFor(model => item.Locatie.name)
            </td>
            <td>
                <a asp-controller="Nieuwsbericht" asp-action="Edit" asp-route-id="@item.NieuwsberichtId">Edit</a> |
                <a asp-controller="Nieuwsbericht" asp-action="Details" asp-route-id="@item.NieuwsberichtId">Details</a> |
                <a asp-controller="Nieuwsbericht" asp-action="Delete" asp-route-id="@item.NieuwsberichtId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>