CommunicatieAppBackend/Models/Melding.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommunicatieAppBackend.Models;

public class Melding{
    [Key]
    public int MeldingId { get; set; }
    public String Titel { get; set; }
    public String Inhoud{ get; set; }
    public DateTime Datum { get; set; }
    [ForeignKey("Locatie")]
    public int LocatieId {get;set;}
    public Locatie Locatie {get;set;}
    public bool Dringend {get;set;}
}

CommunicatieAppBackend/Models/MeldingViewModel.cs
namespace CommunicatieAppBackend.Models;
public class MeldingViewModel
    {
        public Melding melding { get; set; }
        public IEnumerable<Locatie> Locaties {get; set;}
    }

CommunicatieAppBackend/Controllers/MeldingController.cs
using CommunicatieAppBackend.DTOs;
using CommunicatieAppBackend.Hubs;
using CommunicatieAppBackend.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;

namespace CommunicatieAppBackend.Controllers;
public class MeldingController : Controller
{
    private readonly AppDbContext _context;
    private IHubContext<NotificationHub> HubContext{ get; set; }

    public MeldingController(AppDbContext context, IHubContext<NotificationHub> hubcontext)
    {
        HubContext = hubcontext;
        _context = context;
    }
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index(String searchString)
    {
        if (searchString != null)
        {
            return View(_context.meldingen.Where(x => x.Titel.Contains(searchString) || searchString == null).Include(m=>m.Locatie).OrderByDescending(it=>it.Dringend).ThenByDescending(it=>it.Datum).ToList());
        }
        return View(await _context.meldingen.Include(m=>m.Locatie).OrderByDescending(it=>it.Dringend).ThenByDescending(it=>it.Datum).ToListAsync());
    }

    // GET: meldingen/Details/5
    // [Route("Details")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.meldingen == null)
        {
            return NotFound();
        }

        var melding = await _context.meldingen.Include(it=>it.Locatie)
            .FirstOrDefaultAsync(m => m.MeldingId == id);
        if (melding == null)
        {
            return NotFound();
        }

        return View(melding);
    }

    // GET: meldingen/Create
    // [Route("Create")]
    [Authorize(Roles = "Admin")]
    [Route("Melding/Create")]
    public async Task<IActionResult> Create()
    {
        return View(new MeldingViewModel{
            Locaties= await _context.Locaties.ToListAsync()
        });
    }

    // POST: meldingen/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("Melding/Create")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create(MeldingViewModel model)
    {
        model.melding.MeldingId=await _context.meldingen.MaxAsync(it=>it.MeldingId)+1;
        // Console.WriteLine("creating "+model.melding.MeldingId+"..");
        
        if (model!=null)
        {
            var melding = new Melding{
                MeldingId = model.melding.MeldingId,
                Titel = model.melding.Titel,
                Inhoud = model.melding.Inhoud,
                Datum = model.melding.Datum,
                LocatieId = model.melding.LocatieId,
                Locatie = model.melding.Locatie,
                Dringend = model.melding.Dringend
            };
            _context.Add(melding);
            await _context.SaveChangesAsync();
            await HubContext.Clients.All.SendAsync("ReceiveNotification",melding.Titel,melding.Inhoud);
            return RedirectToAction(nameof(Index));
        } else Console.WriteLine("creating failed");
        return RedirectToAction(nameof(Index));
    }

    // GET: meldingen/Edit/5
    // [Route("Melding/Edit")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.meldingen == null)
        {
            return NotFound();
        }

        var melding = await _context.meldingen.FindAsync(id);
        if (melding == null)
        {
            return NotFound();
        }
        return View(new MeldingViewModel{
            Locaties= await _context.Locaties.ToListAsync(),
            melding=melding
        });

    }

    // POST: meldingen/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]  
    // [Route("Melding/Edit")]  
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(int? id, MeldingViewModel mvm)
    {
        Console.WriteLine(id+" "+mvm.Locaties.ToJson()+" "+mvm.melding.Titel);

        if (id != mvm.melding.MeldingId)
        {
            return NotFound();
        }

    
        try
        {
            _context.Update(mvm.melding);
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!meldingExists(mvm.melding.MeldingId))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }
        return RedirectToAction(nameof(Index));
        
    }

    // GET: meldingen/Delete/5
    // [Route("Delete")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.meldingen == null)
        {
            return NotFound();
        }

        var melding = await _context.meldingen.Include(it=>it.Locatie)
            .FirstOrDefaultAsync(m => m.MeldingId == id);
        if (melding == null)
        {
            return NotFound();
        }

        return View(melding);
    }

    // POST: meldingen/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    // [Route("DeleteConfirm")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        if (_context.meldingen == null)
        {
            return Problem("Entity set 'PocketSkillsDbContext.meldingen'  is null.");
        }
        var melding = await _context.meldingen.SingleOrDefaultAsync(it=>it.MeldingId==id);
        if (melding != null)
        {
            Console.WriteLine("removing "+melding.MeldingId+" "+melding.Titel+" "+melding.Inhoud+" "+melding.Datum);
            _context.meldingen.Remove(melding);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        } else return NotFound();
    }

    [Authorize(Roles = "Admin")]
    private bool meldingExists(int id)
    {
        return _context.meldingen.Any(e => e.MeldingId == id);
    }

    [HttpGet]
    [Route("Melding/Get")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
    public async Task<GetMeldingDTO> getAll(){
        return new GetMeldingDTO
        {
            Meldingen = await _context.meldingen.Include(m=>m.Locatie).OrderByDescending(it=>it.Dringend).ThenByDescending(it=>it.Datum).ToListAsync()
        };
    }

    [HttpGet]
    [Route("Melding/GetByLocatie/{Id}")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
    public async Task<GetMeldingDTO> getByLocatie(String Id){
        return new GetMeldingDTO
        {
            Meldingen = await _context.meldingen.Include(m=>m.Locatie).Where(n=>n.Locatie.name==Id).ToListAsync()
        };
    }

    [HttpPost]
    [Route("Melding/ApiCreate")]
    [Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme, Roles ="Admin")]
    public async Task<IActionResult> ApiCreate([FromBody] MeldingDTO model){

        if (!ModelState.IsValid){
            return BadRequest();
        }

        Locatie locatie = await _context.Locaties.SingleAsync(it=>it.name==model.Locatie);
        int MeldingId=await _context.meldingen.MaxAsync(it=>it.MeldingId)+1;

        Melding melding = new Melding{
            Titel = model.Titel,
            Inhoud= model.Inhoud,
            Locatie = locatie,
            LocatieId = locatie.Id,
            MeldingId = MeldingId,
            Datum = DateTime.UtcNow,
            Dringend = model.Dringend
        };

        _context.Add(melding);
        await _context.SaveChangesAsync();
        await HubContext.Clients.All.SendAsync("ReceiveNotification",melding.Titel,melding.Inhoud);
        
        return Ok();
    }
}

CommunicatieAppBackend/Views/Melding/Create.cshtml
@model CommunicatieAppBackend.Models.MeldingViewModel

@{
    ViewData["Title"] = "Create";
    String defaultdt = DateTime.Now.ToString("yyyy-MM-ddThh:mm");
}

<h1>Create</h1>

<h4>Melding</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Melding" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <input type="hidden" asp-for="MeldingId" /> *@
            <div class="form-group">
                <label asp-for="melding.Titel" class="control-label"></label>
                <input asp-for="melding.Titel" class="form-control" />
                <span asp-validation-for="melding.Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="melding.Inhoud" class="control-label"></label>
                <input asp-for="melding.Inhoud" class="form-control" />
                <span asp-validation-for="melding.Inhoud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="melding.Datum" class="control-label"></label>
                <input type="datetime-local" asp-for="melding.Datum" class="form-control" value="@defaultdt" />
                <span asp-validation-for="melding.Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="melding.Locatie"></label>
                <br/>
                @Html.DropDownListFor(  
                    m=>m.melding.LocatieId,
                    new SelectList(Model.Locaties,"Id","name",Model.Locaties.FirstOrDefault()),
                    "--select--"
                )
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="melding.Dringend">
                <label class="form-check-label" asp-for="melding.Dringend">
                    Deze melding is dringend!
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Melding" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunicatieAppBackend/Views/Melding/Delete.cshtml
@model CommunicatieAppBackend.Models.Melding

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Melding</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inhoud)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inhoud)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locatie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locatie.name)
        </dd>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dringend)
        </dd>
    </dl>
    
    <form asp-controller="Melding" asp-action="Delete">
        <input type="hidden" asp-for="MeldingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Melding" asp-action="Index">Back to List</a>
    </form>
</div>

CommunicatieAppBackend/Views/Melding/Details.cshtml
@model CommunicatieAppBackend.Models.Melding

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Melding</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inhoud)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inhoud)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locatie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locatie.name)
        </dd>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dringend)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-controller="Melding" asp-action="Edit" asp-route-id="@Model?.MeldingId">Edit</a> |
    <a asp-controller="Melding" asp-action="Index">Back to List</a>
</div>

CommunicatieAppBackend/Views/Melding/Edit.cshtml
@model CommunicatieAppBackend.Models.MeldingViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Melding</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Melding" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="melding.MeldingId" />
            <div class="form-group">
                <label asp-for="melding.Titel" class="control-label"></label>
                <input asp-for="melding.Titel" class="form-control" />
                <span asp-validation-for="melding.Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="melding.Inhoud" class="control-label"></label>
                <input asp-for="melding.Inhoud" class="form-control" />
                <span asp-validation-for="melding.Inhoud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="melding.Datum" class="control-label"></label>
                <input asp-for="melding.Datum" class="form-control" />
                <span asp-validation-for="melding.Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="melding.Locatie"></label>
                <br/>
                @Html.DropDownListFor(
                    m=>m.melding.LocatieId,
                    new SelectList(Model.Locaties,"Id","name",Model.Locaties.FirstOrDefault()),
                    "--select--"
                )
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="melding.Dringend">
                <label class="form-check-label" asp-for="melding.Dringend">
                    Deze melding is dringend!
                </label>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunicatieAppBackend/Views/Melding/Index.cshtml
@model IEnumerable<CommunicatieAppBackend.Models.Melding>

@{
    ViewData["Title"] = "Index";
}

<h1>Meldingen</h1>

<p>
    <a asp-controller="Melding" asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("Index", "Meldingen", FormMethod.Get))
{
<text>Search:</text> @Html.TextBox("searchString")<input type="submit" name="submit" value="Search" />
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inhoud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Locatie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dringend)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Titel)
            </td>
            <td>
                @Html.DisplayFor(model => item.Inhoud)
            </td>
            <td>
                @Html.DisplayFor(model => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(model => item.Locatie.name)
            </td>
            <td>
                @Html.DisplayFor(model => item.Dringend)
            </td>
            <td>
                <a asp-controller="Melding" asp-action="Edit" asp-route-id="@item.MeldingId">Edit</a> |
                <a asp-controller="Melding" asp-action="Details" asp-route-id="@item.MeldingId">Details</a> |
                <a asp-controller="Melding" asp-action="Delete" asp-route-id="@item.MeldingId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>